name: echovision
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camerawesome: ^2.1.0
  path_provider: ^2.1.5
  get: ^4.7.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Images/logo.png"          # مسار الأيقونة
  adaptive_icon_background: "#FFFFFF"           # خلفية بيضا للأيقونة التكيفية
  adaptive_icon_foreground: "assets/Images/logo.png"  # أيقونة الواجهة التكيفية
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/Images/
